DROP TABLE IF EXISTS sales;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS partners;
-- Создание таблиц
CREATE TABLE partners (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone VARCHAR(25) NOT NULL,
    inn VARCHAR(12) NOT NULL UNIQUE,
    rating NUMERIC(3, 1) NOT NULL DEFAULT 0.0 CHECK (rating >= 0)
);

CREATE TABLE products (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    price DECIMAL(10, 2) NOT NULL CHECK (price >= 0)
);

CREATE TABLE sales (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id INT NOT NULL REFERENCES partners(id) ON DELETE CASCADE,
    product_id INT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    quantity INT NOT NULL CHECK (quantity > 0),
    sale_date DATE NOT NULL DEFAULT CURRENT_DATE
);
-- Заполнение данных
INSERT INTO  products (id, name, price)
VALUES 
(1, 'Стиральный порошок "Альфа"', 500.00),
(2, 'Мыло жидкое "Стандарт"', 90.00),
(3, 'Кондиционер для белья', 350.00);

INSERT INTO partners (id, name, inn, email, phone, rating)
VALUES 
(1, 'ООО "Логистик-Экспресс"', '7701234567', 'info@logex.ru', '+7 (999) 111-22-33', 4.8),
(2, 'ИП Петров А.В.', '5001098765', 'petrov_delivery@mail.ru', '+7 (000) 000-00-00', 4.2),
(3, 'ТК "Быстрый Путь"', '7812345678', 'speedway@yandex.ru', '+7 (812) 555-44-33', 0.0);

INSERT INTO sales (id, partner_id, product_id, quantity, sale_date)
VALUES 
(101, 1, 1, 50, '2026-03-01'),
(102, 2, 2, 200, '2026-03-15'),
(103, 1, 3, 30, '2026-03-20'),
(105, 3, 2, 150, '2026-03-25');
-- проверка запросами
SELECT COUNT(*) AS total_deliveries FROM sales;
SELECT COUNT(*) AS total_products FROM products;
SELECT COUNT(*) AS total_partners FROM partners;
-- Обновление счётчиков
SELECT setval(pg_get_serial_sequence('partners', 'id'), COALESCE(MAX(id), 1)) FROM partners;
SELECT setval(pg_get_serial_sequence('products', 'id'), COALESCE(MAX(id), 1)) FROM products;
SELECT setval(pg_get_serial_sequence('sales', 'id'), COALESCE(MAX(id), 1)) FROM sales;